### ISSUE TITLE
Generated JSON format not equivalent to the documentation

### ISSUE THREAD

**Issue by cartsp** [Vexilla/vexilla.github.io#1]
When looking at the documentation the expected JSON format generated is:

```javascript
{
  environments: {
    [environmentName: string]: {
      [featureSetName: string]: { // currently hardcoded to "untagged"
        [featureName: string]:
          | VexillaToggleFeature
          | VexillaGradualFeature
          | VexillaSelectiveFeature;
      }
    };
  }
}
```

However the generated JSON is in the format:

```javascript
{
   "environments":{
      "dev":{
         "untagged":{
            "billing":{
               "value":100,
               "seed":0.56,
               "type":"gradual"
            },
            "testingNonWorkingGradual":{
               "value":40,
               "seed":0.22,
               "type":"gradual"
            },
            "testingWorkingGradual":{
               "value":40,
               "seed":0.11,
               "type":"gradual"
            }
         }
      },
      "prod":{
         "untagged":{
            "billing":{
               "seed":0.62,
               "value":21,
               "type":"gradual"
            },
            "testingNonWorkingGradual":{
               "value":82,
               "seed":0.01,
               "type":"gradual"
            },
            "testingWorkingGradual":{
               "value":0,
               "seed":0.01,
               "type":"gradual"
            }
         }
      }
   }
}
```

It looks like the documentation's version of the JSON would be the more desireable, using arrays for the environments and feature flags, rather than each being considered a unique object type that the current format is in.  This should also make deserialization easier..

**Comment by cmgriffing** [comment]
First off, I can see the confusion and I need to document that better in that section.

What we have actually does match. The syntax is a TS definition and the brackets are not indicating an array. They just indicate a dynamic string.

I also want to clarify that an object is ideal for our use case because it is a constant time lookup while the array implementation would be linear at best.
