### ISSUE TITLE
Clicking on "License" link doesn't do anything

### ISSUE THREAD

**Issue by philip0524** [Vexilla/vexilla.github.io#3]
As said in the title, when I click on `License` in the header navbar nothing happens.

Additionally, when scrolling to the bottom, you can see the word "License" (picture), which is probably supposed to be placeholder.

![placeholder License in the bottom](https://user-images.githubusercontent.com/72703443/128262715-a963eaae-d902-44cb-afa7-4a07ce63dc81.png)

**Comment by cmgriffing** [comment]
Thanks for pointing this out. There has been a small change and now the MIT license link just links out to the MIT License definition.
