### ISSUE TITLE
Header logo off-center

### ISSUE THREAD

**Issue by premiare** [Vexilla/vexilla.github.io#5]
Logo is off-center in the circle of the header.

Can be fixed by adding `mx-auto` to line 14 in `header.tsx` SeemsGood

[https://github.com/premiare/vexilla.github.io/pull/1/files](url)

**Comment by cmgriffing** [comment]
Sorry, forgot to reply to this. 
Looks great. Feel free to make a PR against this repo and I will merge it in.
